# Generated by Django 5.2.2 on 2025-06-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='profileimage/'),
        ),
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='profileimage/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='profileimage/'),
        ),
    ]
